import {jsPDF} from 'jspdf';
import 'svg2pdf.js';
import {FONT_FILES,MOTIFS,MATERIALS,parseFont,buildGeometry,svgDocument} from './geometry.js';
const $=id=>document.getElementById(id);const initial=()=>({text:'DigiFactory',font:'gemstone',material:'black',textColor:'#ffffff',lineGap:2,width:80,border:2.5,hole:4,decorations:[{shape:'flame',color:'#ff3a30',size:90,gap:1.5}]});let config=initial(),fonts={},geometry,view='result',timer,toastTimer;
const palette=['#2f3a48','#5b60a8','#8c4292','#d5ff3f','#000000','#ffffff'];
function toast(message){$('status').textContent=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('status').textContent='',4500);}
function swatches(id,key){$(id).innerHTML=palette.map(c=>`<button type="button" data-color="${c}" style="background:${c}" aria-label="Choisir ${c}" title="${c}"></button>`).join('');$(id).addEventListener('click',e=>{const c=e.target.dataset.color;if(c){if(key==='text')config.textColor=c;else config.decorations[0].color=c;sync();render();}});}
function icon(key){if(key==='none')return '<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="5"><circle cx="50" cy="50" r="36"/><path d="M24 76 L76 24"/></svg>';const m=MOTIFS[key];return `<svg viewBox="-5 -5 110 110"><path d="${m.d} ${m.cutouts||''}" fill="currentColor" fill-rule="evenodd"/>${m.detail?`<path d="${m.detail}" fill="white"/>`:''}</svg>`;}
$('shapes').innerHTML=Object.entries(MOTIFS).map(([k,m])=>`<button type="button" class="shape-button" data-shape="${k}" aria-label="${m.name}" title="${m.name}">${icon(k)}<span class="shape-name">${m.name}</span></button>`).join('');
function syncLineGap(){const gap=config.lineGap??2;$('line-gap-control').hidden=config.text.split(/\r?\n/).filter(line=>line.trim()).length<2;$('line-gap').value=gap;$('line-gap-value').textContent=`${gap.toLocaleString('fr-BE')} mm`;$('line-gap').setAttribute('aria-valuetext',$('line-gap-value').textContent);}
function sync(){syncLineGap();document.querySelectorAll('[data-material]').forEach(b=>{if(b.tagName!=='BUTTON')return;const on=b.dataset.material===config.material;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',on);});const d=config.decorations[0];$('text').value=config.text;$('char-count').textContent=`${[...config.text].length} / 18`;$('text-color').value=config.textColor;$('text-color-value').textContent=config.textColor.toUpperCase();$('shape-color').value=d.color;$('shape-color-value').textContent=d.color.toUpperCase();$('shape-size').value=d.size;$('shape-size-value').textContent=`${d.size} %`;$('shape-gap').value=d.gap;$('shape-gap').disabled=d.shape==='none';$('shape-gap-value').textContent=`${d.gap.toLocaleString('fr-BE')} mm`;for(const k of ['width','border','hole'])$(k).value=config[k];$('border-value').textContent=`${config.border.toLocaleString('fr-BE')} mm`;$('border').setAttribute('aria-valuetext',$('border-value').textContent);document.querySelectorAll('[data-font]').forEach(b=>{let on=b.dataset.font===config.font;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',on);});document.querySelectorAll('[data-shape]').forEach(b=>{let on=b.dataset.shape===d.shape;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',on);});document.querySelectorAll('[data-view]').forEach(b=>{let on=b.dataset.view===view;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on);});for(const [id,c]of [['text-swatches',config.textColor],['shape-swatches',d.color]])$(id).querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b.dataset.color===c));}
function render(){try{if(!fonts[config.font])return;geometry=buildGeometry(config,fonts[config.font]);$('stage').style.setProperty('--preview-width',geometry.width+'mm');$('stage').innerHTML=svgDocument(geometry,view,true);$('stage').className=`preview-stage mode-${view}`;$('dimensions').textContent=`${geometry.width.toFixed(1)} × ${geometry.height.toFixed(1)} mm`;for(const k of ['export-laser','export-uv','export-png'])$(k).disabled=false;}catch(e){geometry=null;$('stage').replaceChildren();const p=document.createElement('p');p.className='error';p.textContent=e.message;$('stage').append(p);$('dimensions').textContent='Dimensions à ajuster';for(const k of ['export-laser','export-uv','export-png'])$(k).disabled=true;}}
function filename(type){return `porte-cles-${config.text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/gi,'-').replace(/-+/g,'-')}-${type}`;}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);}
async function exportPDF(type){
 if(!geometry)return;
 const g=geometry,name=filename(type==='laser'?'laser':'uv')+'.pdf',button=$(type==='laser'?'export-laser':'export-uv');button.disabled=true;
 const host=document.createElement('div');host.style.cssText='position:fixed;left:-10000px;top:0;pointer-events:none';
 try{
  // SVG numeric coordinates are millimetres; use unitless dimensions to avoid CSS px conversion.
  host.innerHTML=svgDocument(g,type).replace(/width="[^"]+" height="[^"]+"/,`width="${g.width}" height="${g.height}"`);
  document.body.appendChild(host);
  const pdf=new jsPDF({orientation:g.width>=g.height?'landscape':'portrait',unit:'mm',format:[g.width,g.height],precision:8,compress:true});
  pdf.setProperties({title:name,creator:'Digital Factory — Atelier porte-clés'});
  await pdf.svg(host.firstElementChild,{x:0,y:0,width:g.width,height:g.height});
  download(pdf.output('blob'),name);toast('PDF vectoriel exporté à l’échelle 1:1.');
 }catch(e){toast('Le PDF n’a pas pu être préparé. Réessaie.');console.error(e);}finally{host.remove();button.disabled=!geometry;}
}
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
async function withDPI(blob){const png=new Uint8Array(await blob.arrayBuffer()),chunk=new Uint8Array(21),dv=new DataView(chunk.buffer);dv.setUint32(0,9);chunk.set([112,72,89,115],4);dv.setUint32(8,23622);dv.setUint32(12,23622);chunk[16]=1;dv.setUint32(17,crc32(chunk.slice(4,17)));const parts=[png.slice(0,33),chunk];for(let at=33;at<png.length;){const length=new DataView(png.buffer,png.byteOffset+at,4).getUint32(0);const end=at+length+12;if(String.fromCharCode(...png.slice(at+4,at+8))!=='pHYs')parts.push(png.slice(at,end));at=end;}return new Blob(parts,{type:'image/png'});}
async function exportPNG(){if(!geometry)return;const g=geometry,button=$('export-png');button.disabled=true;let url;try{const svg=svgDocument(g,'uv').replace(/width="[^"]+" height="[^"]+"/,`width="${Math.round(g.width/25.4*600)}" height="${Math.round(g.height/25.4*600)}"`);url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));const image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(Error('Le PNG n’a pas pu être préparé.'));image.src=url;});const canvas=document.createElement('canvas');canvas.width=Math.round(g.width/25.4*600);canvas.height=Math.round(g.height/25.4*600);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);const png=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!png)throw Error('Le PNG n’a pas pu être préparé.');download(await withDPI(png),filename('uv-600ppp')+'.png');toast(`PNG transparent exporté · ${canvas.width} × ${canvas.height} pixels · 600 ppp`);}catch(e){toast(e.message);}finally{if(url)URL.revokeObjectURL(url);button.disabled=!geometry;}}
swatches('text-swatches','text');swatches('shape-swatches','shape');$('text').addEventListener('input',e=>{config.text=e.target.value;syncLineGap();$('char-count').textContent=`${[...config.text].length} / 18`;clearTimeout(timer);timer=setTimeout(render,120);});document.querySelectorAll('[data-font]').forEach(b=>b.addEventListener('click',()=>{config.font=b.dataset.font;sync();render();}));$('shapes').addEventListener('click',e=>{const b=e.target.closest('[data-shape]');if(b){config.decorations[0].shape=b.dataset.shape;sync();render();}});document.querySelectorAll('button[data-material]').forEach(b=>b.addEventListener('click',()=>{config.material=b.dataset.material;sync();render();}));document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;sync();render();}));$('text-color').addEventListener('input',e=>{config.textColor=e.target.value;sync();render();});$('shape-color').addEventListener('input',e=>{config.decorations[0].color=e.target.value;sync();render();});$('shape-size').addEventListener('input',e=>{config.decorations[0].size=+e.target.value;sync();render();});$('shape-gap').addEventListener('input',e=>{config.decorations[0].gap=+e.target.value;sync();render();});for(const k of ['width','border','hole'])$(k).addEventListener('input',e=>{config[k]=+e.target.value;if(k==='border'){$('border-value').textContent=`${config.border.toLocaleString('fr-BE')} mm`;$('border').setAttribute('aria-valuetext',$('border-value').textContent);}render();});$('line-gap').addEventListener('input',e=>{config.lineGap=+e.target.value;syncLineGap();render();});$('reset').addEventListener('click',()=>{config=initial();view='result';sync();render();});$('export-laser').addEventListener('click',()=>{render();exportPDF('laser');});$('export-uv').addEventListener('click',()=>{render();exportPDF('uv');});$('export-png').addEventListener('click',()=>{render();exportPNG();});
async function init(){sync();try{for(const [key,path]of Object.entries(FONT_FILES)){const r=await fetch(path);if(!r.ok)throw Error('Les polices ne sont pas disponibles. Recharge la page.');fonts[key]=parseFont(await r.arrayBuffer());}render();registerTools();}catch(e){$('stage').textContent=e.message;}}
function registerTools(){const ctx=document.modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});const tools=[{name:'read_keychain',description:'Lire la composition et les dimensions actuelles du porte-clés.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({composition:structuredClone(config),dimensions:geometry?{width:geometry.width,height:geometry.height}:null})},{name:'configure_keychain',description:'Modifier le texte, la police, la couleur des lettres et le matériau aperçu du porte-clés affiché.',inputSchema:{type:'object',properties:{text:{type:'string',minLength:1,maxLength:18},font:{type:'string',enum:Object.keys(FONT_FILES)},material:{type:'string',enum:Object.keys(MATERIALS)},textColor:{type:'string',pattern:'^#[0-9a-fA-F]{6}$'}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['text','font','textColor','material'].includes(k)))throw Error('Paramètres non reconnus.');if(input.text!==undefined&&(typeof input.text!=='string'||!input.text.trim()||[...input.text].length>18))throw Error('Texte non valide.');if(input.material!==undefined&&!MATERIALS[input.material])throw Error('Matériau non valide.');if(input.font!==undefined&&!FONT_FILES[input.font])throw Error('Police non valide.');if(input.textColor!==undefined&&!/^#[\da-f]{6}$/i.test(input.textColor))throw Error('Couleur non valide.');const next={...config,...input};buildGeometry(next,fonts[next.font]);config=next;sync();render();return {composition:structuredClone(config),dimensions:{width:geometry.width,height:geometry.height}};}}];for(const t of tools){try{Promise.resolve(ctx.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{}}}
init();
