import fs from 'node:fs';
import assert from 'node:assert/strict';
import Clipper from 'clipper-lib';
import {parseFont,buildGeometry,svgDocument,MOTIFS,FONT_FILES} from './geometry.js';
const cfg={text:'Roots',font:'shorebreak',textColor:'#00102a',width:80,border:2.5,hole:4,decorations:[{shape:'star',color:'#ffb92e',size:100}]};
const files=Object.fromEntries(Object.entries(FONT_FILES).map(([key,path])=>[key,path.split('/').at(-1)]));let count=0;
for(const [key,file] of Object.entries(files)){const data=fs.readFileSync('distassets/'+file);const font=parseFont(data.buffer.slice(data.byteOffset,data.byteOffset+data.byteLength));for(const shape of Object.keys(MOTIFS)){const c={...cfg,font:key,text:key==='gemstone'?'Emilie':'Émilie',decorations:[{...cfg.decorations[0],shape}]};const g=buildGeometry(c,font);assert(Math.abs(g.width-80)<.03,`width ${key} ${shape}: ${g.width}`);assert.equal(Clipper.Clipper.PointInPolygon({X:g.hole.x*1000,Y:g.hole.y*1000},g.outer),1);assert(!svgDocument(g,'uv').includes('<text'));assert(!svgDocument(g,'uv').includes('NaN'));if(shape==='crown')assert(!MOTIFS.crown.detail);assert(!svgDocument(g,'laser').includes('<g'));assert(svgDocument(g,'laser').includes('stroke-width="0.01"'));assert(svgDocument(g,'uv').includes(`width="${g.width}mm" height="${g.height}mm"`));if(shape==='star')fs.writeFileSync('/tmp/keychain-'+key+'.svg',svgDocument(g,'result'));count++;}
for(const text of (key==='gemstone'?['Jean Luc','Aicha','Eleonore','WWW','i','i j','DigitalFactory2026']:['Jean Luc','Aïcha','Éléonore','WWW','i','i j','DigitalFactory2026'])){const g=buildGeometry({...cfg,text,width:120,decorations:[{shape:'crown',color:'#9b5de5',size:140}]},font);assert(Math.abs(g.width-120)<.03);count++;}
for(const width of [40,140]){const g=buildGeometry({...cfg,text:'Tom',width},font);assert(Math.abs(g.width-width)<.03);count++;}if(key==='gemstone'){for(const text of ['Émilie'])assert.throws(()=>buildGeometry({...cfg,font:key,text},font),/Gemstone/);}assert.throws(()=>buildGeometry({...cfg,text:''},font));assert.throws(()=>buildGeometry({...cfg,text:'\u{10FFFF}'},font));}
console.log(`${count} compositions vérifiées : dimensions, trou intégré, tracés vectoriels et exports.`);
